#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:
# displays "bad luck" for 4th loop iteration
# displays "good luck" for 8th loop iteration
# displays "Best School" for the other iterations

count=0
while [ $count -lt 10 ]
do
	if [ $count = 3 ]
	then
		echo "bad luck"
	elif [ $count = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
