#!/usr/bin/env bash
# Bash script that gives you information about the school file.

f=school
if [ -e "$f" ]
then
	echo "school file exists"
	if [ -s "$f" ]
	then
		echo "school file does not exist"
	else
		echo "school file is empty"
	fi
	if [ -f "$f" ]
	then
		echo "school file is not empty"
	fi
else
	echo "school is a regular file"
fi
